### ISSUE TITLE
Adding X-learner framework

### ISSUE THREAD

**Issue by MaximilianFranz** [rguo12/awesome-causality-algorithms#1]
Hey :) 

I wanted to propose adding the X-learner meta-learner framework for heterogeneous treatment effects. 

Paper: https://www.pnas.org/content/pnas/116/10/4156.full.pdf
Code: https://github.com/xnie/rlearner/blob/master/R/xlearner.R

I guess this belongs to the i.i.d data section. 

Thanks for the awesome collection and the comprehensive review paper, great work!

**Comment by rguo12** [comment]
Thanks a lot, Maximilian! I will do it soon.

**Comment by rguo12** [comment]
X-learner is added.
