### ISSUE TITLE
Add a new work on estimating causal effects under confounding

### ISSUE THREAD

**Issue by wpzdm** [rguo12/awesome-causality-algorithms#14]
Shamelessly recommend my own preprint:
https://arxiv.org/abs/2101.06662
Some highlights: https://twitter.com/PengzhouW/status/1362225064309972993
In particular, it shows SOTA performance of balancing and deconfounding on IHDP and Pokec.

I do not know if preprints are allowed by the policy of your list. Simply ignore this if not.

**Comment by rguo12** [comment]
Hi Pengzhou,

If you could create a pull request for the suggested work, that would be
great as github would list you as a contributor to the repository.

Best regards,

Ruocheng

**Comment by rguo12** [comment]
added. Thx for the suggestion.
