### ISSUE TITLE
Adding Causal Transformer from pre-print "Causal Transformer for Estimating Counterfactual Outcomes"

### ISSUE THREAD

**Issue by Valentyn1997** [rguo12/awesome-causality-algorithms#27]
I wanted to modestly propose expanding "Learning Time Varying/Dependent Causal Effects" section with our pre-print ["Causal Transformer for Estimating Counterfactual Outcomes"](https://arxiv.org/abs/2204.07258).

The code (https://github.com/Valentyn1997/CausalTransformer) also contains the PyTorch-Lightning implementation of other baselines over time, e.g., CRN, RMSN or MSMs.

I can create a corresponding pull request if you don't mind. 

Best regards,
Valentyn

**Comment by rguo12** [comment]
added
