### ISSUE TITLE
Adding DAG and TCDF frameworks?

### ISSUE THREAD

**Issue by amunishkin** [rguo12/awesome-causality-algorithms#6]
Hi,

Would the following frameworks work for this repo?

Timeseries non-i.d.d. data
- TCDF: Temporal Causal Discovery Framework (https://github.com/M-Nauta/TCDF)

Structured Learning i.d.d. data
- DAG-GNN (https://github.com/fishmoon1234/DAG-GNN)
- DAGs with NO TEARS (https://github.com/xunzheng/notears)

Thanks!

**Comment by rguo12** [comment]
Thanks! I will add them soon.

**Comment by rguo12** [comment]
The suggested papers and code repos are added. Thanks for the suggestion!
