### ISSUE TITLE
Add paper to NLP section

### ISSUE THREAD

**Issue by kakeith** [rguo12/awesome-causality-algorithms#7]
Hi! I'm not sure if I'm supposed to fork the repo or just leave a comment, but do you mind adding this paper to the NLP section: 

https://www.aclweb.org/anthology/2020.acl-main.474.pdf (ACL2020) 

Thanks!

**Comment by rguo12** [comment]
Thanks for the suggestion, I will do the update during weekend.

**Comment by rguo12** [comment]
Finally I did this! Closing the issue.
